type CosmeticItem = {
  id: string          // уникальный идентификатор (начинается с "cos-")
  name: string        // название препарата
  description: string // краткое описание

  price_sm: number            // цена малой упаковки
  weight_sm: number           // вес малой упаковки в граммах
  active_component_sm: number // количество активного вещества в малой упаковке (мг)
  dosage_sm: number           // количество доз/таблеток в малой упаковке

  price_lg: number            // цена большой упаковки
  weight_lg: number           // вес большой упаковки в граммах
  active_component_lg: number // количество активного вещества в большой упаковке (мг)
  dosage_lg: number           // количество доз/таблеток в большой упаковке

  rating: number | null       // рейтинг препарата (0-5)
  is_promo: boolean           // участвует в акциях
  is_new: boolean             // новинка
  is_top: boolean             // топ продаж
  is_herbal: boolean          // растительного происхождения
  is_profit: boolean          // специальное предложение

  old_price_sm: number        // старая цена малой упаковки (для отображения скидки)
  old_price_lg: number        // старая цена большой упаковки
  promo_title: string         // название акции ("Выгода", "Новинка" и т.д.)

  img_url: string             // URL изображения препарата
  category: string            // категория (например: "антибиотики", "витамины")
  manufacturer: string        // производитель
  requires_prescription: boolean // требуется рецепт
}

const cosmeticItems: CosmeticItem[] = [
  {
    id: "cos-001",
    name: "Hydra Boost Moisturizer",
    description: "Легкий увлажняющий крем с гиалуроновой кислотой",
    price_sm: 850,
    weight_sm: 50,
    active_component_sm: 100,
    dosage_sm: 1,
    price_lg: 1200,
    weight_lg: 100,
    active_component_lg: 200,
    dosage_lg: 1,
    rating: 4.8,
    is_promo: true,
    is_new: false,
    is_top: true,
    is_herbal: false,
    is_profit: true,
    old_price_sm: 950,
    old_price_lg: 1400,
    promo_title: "Выгода",
    img_url: "/cosmetic-items/cosmetic-1.webp",
    category: "skincare",
    manufacturer: "DermActive",
    requires_prescription: false,
  },
  {
    id: "cos-002",
    name: "Daily Defense Sunscreen SPF 50",
    description: "Солнцезащитный крем широкого спектра действия",
    price_sm: 780,
    weight_sm: 30,
    active_component_sm: 50,
    dosage_sm: 1,
    price_lg: 1300,
    weight_lg: 60,
    active_component_lg: 100,
    dosage_lg: 1,
    rating: 4.6,
    is_promo: false,
    is_new: true,
    is_top: true,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/cosmetic-items/cosmetic-1.webp",
    category: "skincare",
    manufacturer: "SunGuard",
    requires_prescription: false,
  },
  {
    id: "cos-003",
    name: "Revital Eye Serum",
    description: "Сыворотка для кожи вокруг глаз с кофеином",
    price_sm: 950,
    weight_sm: 15,
    active_component_sm: 20,
    dosage_sm: 1,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.7,
    is_promo: false,
    is_new: true,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/cosmetic-items/cosmetic-1.webp",
    category: "skincare",
    manufacturer: "EyeCare Lab",
    requires_prescription: false,
  },
  {
    id: "cos-004",
    name: "Pure Aloe Vera Gel",
    description: "Успокаивающий гель с экстрактом алоэ вера",
    price_sm: 450,
    weight_sm: 100,
    active_component_sm: 50,
    dosage_sm: 1,
    price_lg: 800,
    weight_lg: 200,
    active_component_lg: 100,
    dosage_lg: 1,
    rating: 4.5,
    is_promo: true,
    is_new: false,
    is_top: false,
    is_herbal: true,
    is_profit: true,
    old_price_sm: 500,
    old_price_lg: 900,
    promo_title: "Выгода",
    img_url: "/cosmetic-items/cosmetic-1.webp",
    category: "body care",
    manufacturer: "NatureSkin",
    requires_prescription: false,
  },
  {
    id: "cos-005",
    name: "Volume Lash Mascara",
    description: "Тушь для ресниц с эффектом объема",
    price_sm: 650,
    weight_sm: 10,
    active_component_sm: 0,
    dosage_sm: 1,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.4,
    is_promo: false,
    is_new: false,
    is_top: true,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/cosmetic-items/cosmetic-1.webp",
    category: "makeup",
    manufacturer: "GlamourPro",
    requires_prescription: false,
  },
  {
    id: "cos-006",
    name: "Argan Oil Hair Elixir",
    description: "Питательное масло для волос с аргановым маслом",
    price_sm: 700,
    weight_sm: 50,
    active_component_sm: 30,
    dosage_sm: 1,
    price_lg: 1200,
    weight_lg: 100,
    active_component_lg: 60,
    dosage_lg: 1,
    rating: 4.6,
    is_promo: true,
    is_new: false,
    is_top: false,
    is_herbal: true,
    is_profit: true,
    old_price_sm: 800,
    old_price_lg: 1400,
    promo_title: "Выгода",
    img_url: "/cosmetic-items/cosmetic-1.webp",
    category: "haircare",
    manufacturer: "HairVital",
    requires_prescription: false,
  },
  {
    id: "cos-007",
    name: "Purifying Clay Mask",
    description: "Очищающая маска с белой глиной",
    price_sm: 500,
    weight_sm: 60,
    active_component_sm: 40,
    dosage_sm: 1,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.2,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: true,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/cosmetic-items/cosmetic-1.webp",
    category: "skincare",
    manufacturer: "ClayLab",
    requires_prescription: false,
  },
  {
    id: "cos-008",
    name: "Lip Repair Balm",
    description: "Восстанавливающий бальзам для губ с витамином E",
    price_sm: 320,
    weight_sm: 15,
    active_component_sm: 10,
    dosage_sm: 1,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.7,
    is_promo: false,
    is_new: true,
    is_top: true,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/cosmetic-items/cosmetic-1.webp",
    category: "skincare",
    manufacturer: "SoftLips",
    requires_prescription: false,
  },
  {
    id: "cos-009",
    name: "Revive Night Cream",
    description: "Ночной крем с ретинолом для омоложения",
    price_sm: 1100,
    weight_sm: 50,
    active_component_sm: 0.5,
    dosage_sm: 1,
    price_lg: 2000,
    weight_lg: 100,
    active_component_lg: 1,
    dosage_lg: 1,
    rating: 4.9,
    is_promo: true,
    is_new: true,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "Новинка",
    img_url: "/cosmetic-items/cosmetic-1.webp",
    category: "skincare",
    manufacturer: "Regenix",
    requires_prescription: false,
  },
  {
    id: "cos-010",
    name: "Citrus Fresh Body Wash",
    description: "Освежающий гель для душа с экстрактом цитрусов",
    price_sm: 450,
    weight_sm: 250,
    active_component_sm: 20,
    dosage_sm: 1,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.3,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: true,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/cosmetic-items/cosmetic-1.webp",
    category: "body care",
    manufacturer: "Fresh&Clean",
    requires_prescription: false,
  },
];
export default cosmeticItems;