type DrinkItem = {
  id: string
  name: string
  description: string
  price: number
  is_promo: boolean
  is_new: boolean
  is_profit: boolean
  old_price: number
  promo_title: string
  img_url: string
}

const drinkItems: DrinkItem[] = [
  {
    id: '101',
    name: 'Добрый Кола',
    description: 'Сильногазированный напиток',
    price: 90,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/cola.png',
  },
  {
    id: '102',
    name: 'Добрый Кола без сахара',
    description: 'Сильногазированный напиток без добавления сахара',
    price: 90,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/cola-zero.png',
  },
  {
    id: '103',
    name: 'Добрый лимон-лайм',
    description: 'Сильногазированный напиток',
    price: 90,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/lime.png',
  },
  {
    id: '104',
    name: 'Добрый апельсин',
    description: 'Сильногазированный напиток',
    price: 90,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/orange.png',
  },
  {
    id: '105',
    name: 'Добрый манго-маракуйя',
    description: 'Сильногазированный напиток',
    price: 90,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/mango.png',
  },
  {
    id: '201',
    name: 'Яблочный сок Rich',
    description: '100% яблочный сок',
    price: 190,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/rich_apple.png',
  },
  {
    id: '202',
    name: 'Апельсиновый сок Rich',
    description: '100% апельсиновый сок',
    price: 190,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/rich_orange.png',
  },
  {
    id: '205',
    name: 'Вишневый нектар Rich',
    description: '',
    price: 190,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/rich_cherry.png',
  },
  {
    id: '301',
    name: 'Rich tea лимон',
    description: 'Черный чай Рич со вкусом лимона',
    price: 109,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/tea_lemon.png',
  },
  {
    id: '302',
    name: 'Rich tea зеленый',
    description: 'Зеленый чай Рич',
    price: 109,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/tea_green.png',
  },
  {
    id: '303',
    name: 'Rich tea зеленый c манго',
    description: 'Зеленый чай со вкусом манго',
    price: 109,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/tea_green.png',
  },
  {
    id: '304',
    name: 'Вода BonaAqua негазированная',
    description: '',
    price: 70,
    is_promo: false,
    is_new: false,
    is_profit: false,
    old_price: 999,
    promo_title: '',
    img_url: '/drinks-photo/bonaqua.png',
  },
]

export default drinkItems