type MedicineItem = {
  id: string          // уникальный идентификатор (начинается с "med-")
  name: string        // название препарата
  description: string // краткое описание

  price_sm: number            // цена малой упаковки
  weight_sm: number           // вес малой упаковки в граммах
  active_component_sm: number // количество активного вещества в малой упаковке (мг)
  dosage_sm: number           // количество доз/таблеток в малой упаковке

  price_lg: number            // цена большой упаковки
  weight_lg: number           // вес большой упаковки в граммах
  active_component_lg: number // количество активного вещества в большой упаковке (мг)
  dosage_lg: number           // количество доз/таблеток в большой упаковке

  rating: number | null       // рейтинг препарата (0-5)
  is_promo: boolean           // участвует в акциях
  is_new: boolean             // новинка
  is_top: boolean             // топ продаж
  is_herbal: boolean          // растительного происхождения
  is_profit: boolean          // специальное предложение

  old_price_sm: number        // старая цена малой упаковки (для отображения скидки)
  old_price_lg: number        // старая цена большой упаковки
  promo_title: string         // название акции ("Выгода", "Новинка" и т.д.)

  img_url: string             // URL изображения препарата
  category: string            // категория (например: "антибиотики", "витамины")
  manufacturer: string        // производитель
  requires_prescription: boolean // требуется рецепт
}

const otcMedicines: MedicineItem[] = [
  {
    id: "med-001",
    name: "Парацетамол",
    description: "Обезболивающее и жаропонижающее средство",
    price_sm: 120,
    weight_sm: 50,
    active_component_sm: 500,
    dosage_sm: 10,
    price_lg: 200,
    weight_lg: 100,
    active_component_lg: 1000,
    dosage_lg: 20,
    rating: 1,
    is_promo: true,
    is_new: false,
    is_top: true,
    is_herbal: false,
    is_profit: true,
    old_price_sm: 150,
    old_price_lg: 250,
    promo_title: "Выгода",
    img_url: "/medicine-items/medicine-item-1.webp",
    category: "обезболивающие",
    manufacturer: "ФармаПродукт",
    requires_prescription: false,
  },
  {
    id: "med-002",
    name: "Ибупрофен",
    description: "Нестероидное противовоспалительное средство",
    price_sm: 130,
    weight_sm: 30,
    active_component_sm: 200,
    dosage_sm: 20,
    price_lg: 230,
    weight_lg: 60,
    active_component_lg: 400,
    dosage_lg: 40,
    rating: 2,
    is_promo: false,
    is_new: false,
    is_top: true,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/medicine-items/medicine-item-1.webp",
    category: "противовоспалительные",
    manufacturer: "МедиФарм",
    requires_prescription: false,
  },
  {
    id: "med-003",
    name: "Аспирин (ацетилсалициловая кислота)",
    description: "Анальгетик и антивоспалительное средство",
    price_sm: 90,
    weight_sm: 25,
    active_component_sm: 500,
    dosage_sm: 10,
    price_lg: 160,
    weight_lg: 50,
    active_component_lg: 1000,
    dosage_lg: 20,
    rating: 3,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/medicine-items/medicine-item-1.webp",
    category: "обезболивающие",
    manufacturer: "АптекаПро",
    requires_prescription: false,
  },
  {
    id: "med-004",
    name: "Витамин C 1000",
    description: "Поддержка иммунитета",
    price_sm: 250,
    weight_sm: 40,
    active_component_sm: 1000,
    dosage_sm: 30,
    price_lg: 400,
    weight_lg: 80,
    active_component_lg: 2000,
    dosage_lg: 60,
    rating: 4,
    is_promo: true,
    is_new: true,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "Новинка",
    img_url: "/medicine-items/medicine-item-1.webp",
    category: "витамины",
    manufacturer: "HealthPlus",
    requires_prescription: false,
  },
  {
    id: "med-005",
    name: "Глицин",
    description: "Нормализация сна и снижение стресса",
    price_sm: 80,
    weight_sm: 20,
    active_component_sm: 100,
    dosage_sm: 50,
    price_lg: 140,
    weight_lg: 40,
    active_component_lg: 200,
    dosage_lg: 100,
    rating: 5,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/medicine-items/medicine-item-1.webp",
    category: "успокаивающие",
    manufacturer: "Здравник",
    requires_prescription: false,
  },
  {
    id: "med-006",
    name: "Лоперамид",
    description: "Средство от диареи",
    price_sm: 150,
    weight_sm: 25,
    active_component_sm: 2,
    dosage_sm: 10,
    price_lg: 270,
    weight_lg: 50,
    active_component_lg: 4,
    dosage_lg: 20,
    rating: 6,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/medicine-items/medicine-item-1.webp",
    category: "противодиарейные",
    manufacturer: "ФармЭкс",
    requires_prescription: false,
  },
  {
    id: "med-007",
    name: "Корвалол",
    description: "Седативное и спазмолитическое средство",
    price_sm: 95,
    weight_sm: 30,
    active_component_sm: 20,
    dosage_sm: 25,
    price_lg: 170,
    weight_lg: 60,
    active_component_lg: 40,
    dosage_lg: 50,
    rating: 7,
    is_promo: true,
    is_new: false,
    is_top: false,
    is_herbal: true,
    is_profit: true,
    old_price_sm: 120,
    old_price_lg: 200,
    promo_title: "Выгода",
    img_url: "/medicine-items/medicine-item-1.webp",
    category: "седативные",
    manufacturer: "Биоком",
    requires_prescription: false,
  },
  {
    id: "med-008",
    name: "Маалокс",
    description: "Антацидное средство для снижения кислотности",
    price_sm: 180,
    weight_sm: 150,
    active_component_sm: 0,
    dosage_sm: 20,
    price_lg: 300,
    weight_lg: 300,
    active_component_lg: 0,
    dosage_lg: 40,
    rating: 8,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/medicine-items/medicine-item-1.webp",
    category: "антисекреторные",
    manufacturer: "ГастроЛайн",
    requires_prescription: false,
  },
  {
    id: "med-009",
    name: "Диосмектит (Смекта)",
    description: "Смектит для лечения диареи и гастрита",
    price_sm: 200,
    weight_sm: 60,
    active_component_sm: 3,
    dosage_sm: 10,
    price_lg: 350,
    weight_lg: 120,
    active_component_lg: 6,
    dosage_lg: 20,
    rating: 9,
    is_promo: false,
    is_new: false,
    is_top: true,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/medicine-items/medicine-item-1.webp",
    category: "противодиарейные",
    manufacturer: "Вертекс",
    requires_prescription: false,
  },
  {
    id: "med-010",
    name: "Мятные капли",
    description: "Гомеопатический препарат при головной боли",
    price_sm: 140,
    weight_sm: 30,
    active_component_sm: 0,
    dosage_sm: 20,
    price_lg: 260,
    weight_lg: 60,
    active_component_lg: 0,
    dosage_lg: 40,
    rating: 10,
    is_promo: true,
    is_new: true,
    is_top: false,
    is_herbal: true,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "Новинка",
    img_url: "/medicine-items/medicine-item-1.webp",
    category: "гомеопатия",
    manufacturer: "Зеленая Аптека",
    requires_prescription: false,
  },
]

export default otcMedicines;