type MedtechnicItem = {
  id: string          // уникальный идентификатор (начинается с "tec-")
  name: string        // название препарата
  description: string // краткое описание

  price_sm: number            // цена малой упаковки
  weight_sm: number           // вес малой упаковки в граммах
  active_component_sm: number // количество активного вещества в малой упаковке (мг)
  dosage_sm: number           // количество доз/таблеток в малой упаковке

  price_lg: number            // цена большой упаковки
  weight_lg: number           // вес большой упаковки в граммах
  active_component_lg: number // количество активного вещества в большой упаковке (мг)
  dosage_lg: number           // количество доз/таблеток в большой упаковке

  rating: number | null       // рейтинг препарата (0-5)
  is_promo: boolean           // участвует в акциях
  is_new: boolean             // новинка
  is_top: boolean             // топ продаж
  is_herbal: boolean          // растительного происхождения
  is_profit: boolean          // специальное предложение

  old_price_sm: number        // старая цена малой упаковки (для отображения скидки)
  old_price_lg: number        // старая цена большой упаковки
  promo_title: string         // название акции ("Выгода", "Новинка" и т.д.)

  img_url: string             // URL изображения препарата
  category: string            // категория (например: "антибиотики", "витамины")
  manufacturer: string        // производитель
  requires_prescription: boolean // требуется рецепт
}

const medtechnicItems: MedtechnicItem[] = [
  {
    id: "tec-101",
    name: "Ингалятор компрессорный Omron CompAir C28",
    description: "Эффективная терапия при заболеваниях дыхательных путей",
    price_sm: 2500,
    weight_sm: 600,
    active_component_sm: 0,
    dosage_sm: 0,
    price_lg: 4200,
    weight_lg: 1200,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.7,
    is_promo: true,
    is_new: false,
    is_top: true,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 3000,
    old_price_lg: 4800,
    promo_title: "Выгода",
    img_url: "/medtechnic-items/medtechnic-01.webp",
    category: "ингаляторы",
    manufacturer: "Omron",
    requires_prescription: false
  },
  {
    id: "tec-102",
    name: "Ингалятор ультразвуковой Med2000 Prestige U",
    description: "Бесшумная и бережная доставка лекарства",
    price_sm: 3200,
    weight_sm: 550,
    active_component_sm: 0,
    dosage_sm: 0,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.5,
    is_promo: false,
    is_new: true,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "Новинка",
    img_url: "/medtechnic-items/medtechnic-01.webp",
    category: "ингаляторы",
    manufacturer: "Med2000",
    requires_prescription: false
  },
  {
    id: "tec-103",
    name: "Тонометр автоматический Omron M3 Comfort",
    description: "Измерение артериального давления и пульса",
    price_sm: 2800,
    weight_sm: 300,
    active_component_sm: 0,
    dosage_sm: 0,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.8,
    is_promo: true,
    is_new: false,
    is_top: true,
    is_herbal: false,
    is_profit: true,
    old_price_sm: 3200,
    old_price_lg: 0,
    promo_title: "Специальное предложение",
    img_url: "/medtechnic-items/medtechnic-01.webp",
    category: "тонометры",
    manufacturer: "Omron",
    requires_prescription: false
  },
  {
    id: "tec-104",
    name: "Глюкометр Accu-Chek Active",
    description: "Быстрое определение уровня глюкозы в крови",
    price_sm: 1700,
    weight_sm: 150,
    active_component_sm: 0,
    dosage_sm: 0,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.4,
    is_promo: false,
    is_new: false,
    is_top: true,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/medtechnic-items/medtechnic-01.webp",
    category: "глюкометры",
    manufacturer: "Roche",
    requires_prescription: false
  },
  {
    id: "tec-105",
    name: "Термометр электронный Microlife MT 125",
    description: "Точный бесконтактный измеритель температуры",
    price_sm: 2200,
    weight_sm: 100,
    active_component_sm: 0,
    dosage_sm: 0,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.6,
    is_promo: true,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: true,
    old_price_sm: 2500,
    old_price_lg: 0,
    promo_title: "Выгода",
    img_url: "/medtechnic-items/medtechnic-01.webp",
    category: "термометры",
    manufacturer: "Microlife",
    requires_prescription: false
  },
  {
    id: "tec-106",
    name: "Концентратор кислорода Armed 8F-5L",
    description: "Непрерывная подача кислорода до 5 л/мин",
    price_sm: 15000,
    weight_sm: 10000,
    active_component_sm: 0,
    dosage_sm: 0,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.3,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/medtechnic-items/medtechnic-01.webp",
    category: "кислородные концентраторы",
    manufacturer: "Armed",
    requires_prescription: false
  },
  {
    id: "tec-107",
    name: "Ингалятор меш-тах OmniNeb NE-C801",
    description: "Компактный mesh-ингалятор для детей и взрослых",
    price_sm: 5500,
    weight_sm: 200,
    active_component_sm: 0,
    dosage_sm: 0,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.9,
    is_promo: true,
    is_new: true,
    is_top: true,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "Новинка",
    img_url: "/medtechnic-items/medtechnic-01.webp",
    category: "ингаляторы",
    manufacturer: "Omron",
    requires_prescription: false
  },
  {
    id: "tec-108",
    name: "Пульсоксиметр Riester ri-fox 310",
    description: "Мониторинг SpO2 и пульса на кончике пальца",
    price_sm: 900,
    weight_sm: 50,
    active_component_sm: 0,
    dosage_sm: 0,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.2,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/medtechnic-items/medtechnic-01.webp",
    category: "пульсоксиметры",
    manufacturer: "Riester",
    requires_prescription: false
  },
  {
    id: "tec-109",
    name: "Аппарат для микроклизм Clismaxon",
    description: "Устройство для гидроклизмы в домашних условиях",
    price_sm: 1800,
    weight_sm: 400,
    active_component_sm: 0,
    dosage_sm: 0,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 3.8,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/medtechnic-items/medtechnic-01.webp",
    category: "аппараты для клизм",
    manufacturer: "Clismaxon",
    requires_prescription: false
  },
  {
    id: "tec-110",
    name: "Небулайзер B.Well WN-115",
    description: "Ультразвуковой ингалятор для целой семьи",
    price_sm: 4600,
    weight_sm: 350,
    active_component_sm: 0,
    dosage_sm: 0,
    price_lg: 0,
    weight_lg: 0,
    active_component_lg: 0,
    dosage_lg: 0,
    rating: 4.0,
    is_promo: true,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: true,
    old_price_sm: 5200,
    old_price_lg: 0,
    promo_title: "Выгода",
    img_url: "/medtechnic-items/medtechnic-01.webp",
    category: "ингаляторы",
    manufacturer: "B.Well",
    requires_prescription: false
  }
];

export default medtechnicItems;
