type VitaminItem = {
  id: string          // уникальный идентификатор (начинается с "vit-")
  name: string        // название препарата
  description: string // краткое описание

  price_sm: number            // цена малой упаковки
  weight_sm: number           // вес малой упаковки в граммах
  active_component_sm: number // количество активного вещества в малой упаковке (мг)
  dosage_sm: number           // количество доз/таблеток в малой упаковке

  price_lg: number            // цена большой упаковки
  weight_lg: number           // вес большой упаковки в граммах
  active_component_lg: number // количество активного вещества в большой упаковке (мг)
  dosage_lg: number           // количество доз/таблеток в большой упаковке

  rating: number | null       // рейтинг препарата (0-5)
  is_promo: boolean           // участвует в акциях
  is_new: boolean             // новинка
  is_top: boolean             // топ продаж
  is_herbal: boolean          // растительного происхождения
  is_profit: boolean          // специальное предложение

  old_price_sm: number        // старая цена малой упаковки (для отображения скидки)
  old_price_lg: number        // старая цена большой упаковки
  promo_title: string         // название акции ("Выгода", "Новинка" и т.д.)

  img_url: string             // URL изображения препарата
  category: string            // категория (например: "антибиотики", "витамины")
  manufacturer: string        // производитель
  requires_prescription: boolean // требуется рецепт
}

const vitamins: VitaminItem[] = [
  {
    id: "vit-011",
    name: "Витамин C 500",
    description: "Укрепляет иммунитет, антиоксидант",
    price_sm: 180,
    weight_sm: 30,
    active_component_sm: 500,
    dosage_sm: 20,
    price_lg: 320,
    weight_lg: 60,
    active_component_lg: 1000,
    dosage_lg: 40,
    rating: 4.7,
    is_promo: true,
    is_new: false,
    is_top: true,
    is_herbal: false,
    is_profit: true,
    old_price_sm: 200,
    old_price_lg: 350,
    promo_title: "Выгода",
    img_url: "/vitamins/vitamin-1.webp",
    category: "витамины",
    manufacturer: "HealthPlus",
    requires_prescription: false,
  },
  {
    id: "vit-012",
    name: "Витамин D3 1000 IU",
    description: "Поддержка здоровья костей и иммунитета",
    price_sm: 220,
    weight_sm: 25,
    active_component_sm: 25,
    dosage_sm: 30,
    price_lg: 380,
    weight_lg: 50,
    active_component_lg: 50,
    dosage_lg: 60,
    rating: 4.8,
    is_promo: false,
    is_new: true,
    is_top: true,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/vitamins/vitamin-1.webp",
    category: "витамины",
    manufacturer: "SunVitamin",
    requires_prescription: false,
  },
  {
    id: "vit-013",
    name: "Мультивитамины для женщин",
    description: "Комплекс витаминов и минералов",
    price_sm: 350,
    weight_sm: 40,
    active_component_sm: 0,
    dosage_sm: 30,
    price_lg: 600,
    weight_lg: 80,
    active_component_lg: 0,
    dosage_lg: 60,
    rating: 4.5,
    is_promo: true,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: true,
    old_price_sm: 400,
    old_price_lg: 700,
    promo_title: "Выгода",
    img_url: "/vitamins/vitamin-1.webp",
    category: "комплексы витаминов",
    manufacturer: "WellLife",
    requires_prescription: false,
  },
  {
    id: "vit-014",
    name: "Омега-3 1000 мг",
    description: "Поддержка сердечно-сосудистой системы",
    price_sm: 400,
    weight_sm: 60,
    active_component_sm: 1000,
    dosage_sm: 30,
    price_lg: 720,
    weight_lg: 120,
    active_component_lg: 2000,
    dosage_lg: 60,
    rating: 4.6,
    is_promo: false,
    is_new: false,
    is_top: true,
    is_herbal: true,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/vitamins/vitamin-1.webp",
    category: "биологически активные добавки",
    manufacturer: "OmegaPure",
    requires_prescription: false,
  },
  {
    id: "vit-015",
    name: "Витамин B12 1000 мкг",
    description: "Нормализация работы нервной системы",
    price_sm: 300,
    weight_sm: 20,
    active_component_sm: 1,
    dosage_sm: 30,
    price_lg: 520,
    weight_lg: 40,
    active_component_lg: 2,
    dosage_lg: 60,
    rating: 4.4,
    is_promo: true,
    is_new: true,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "Новинка",
    img_url: "/vitamins/vitamin-1.webp",
    category: "витамины",
    manufacturer: "NeuroHealth",
    requires_prescription: false,
  },
  {
    id: "vit-016",
    name: "Кальций + Магний",
    description: "Поддержка костей и мышц",
    price_sm: 280,
    weight_sm: 50,
    active_component_sm: 500,
    dosage_sm: 30,
    price_lg: 500,
    weight_lg: 100,
    active_component_lg: 1000,
    dosage_lg: 60,
    rating: 4.3,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/vitamins/vitamin-1.webp",
    category: "минералы",
    manufacturer: "MineralWell",
    requires_prescription: false,
  },
  {
    id: "vit-017",
    name: "Железо Форте",
    description: "Препарат для коррекции железодефицита",
    price_sm: 330,
    weight_sm: 40,
    active_component_sm: 65,
    dosage_sm: 20,
    price_lg: 600,
    weight_lg: 80,
    active_component_lg: 130,
    dosage_lg: 40,
    rating: 4.2,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/vitamins/vitamin-1.webp",
    category: "минералы",
    manufacturer: "Hematogenix",
    requires_prescription: false,
  },
  {
    id: "vit-018",
    name: "Пробиотики Лактобактерии",
    description: "Нормализация микрофлоры кишечника",
    price_sm: 290,
    weight_sm: 30,
    active_component_sm: 1,
    dosage_sm: 20,
    price_lg: 540,
    weight_lg: 60,
    active_component_lg: 2,
    dosage_lg: 40,
    rating: 4.5,
    is_promo: true,
    is_new: false,
    is_top: false,
    is_herbal: true,
    is_profit: true,
    old_price_sm: 320,
    old_price_lg: 600,
    promo_title: "Акция",
    img_url: "/vitamins/vitamin-1.webp",
    category: "биологически активные добавки",
    manufacturer: "BioFlora",
    requires_prescription: false,
  },
  {
    id: "vit-019",
    name: "Коллаген + Гиалуроновая кислота",
    description: "Для здоровья кожи и суставов",
    price_sm: 450,
    weight_sm: 60,
    active_component_sm: 1000,
    dosage_sm: 30,
    price_lg: 800,
    weight_lg: 120,
    active_component_lg: 2000,
    dosage_lg: 60,
    rating: 4.6,
    is_promo: false,
    is_new: true,
    is_top: false,
    is_herbal: false,
    is_profit: false,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/vitamins/vitamin-1.webp",
    category: "биологически активные добавки",
    manufacturer: "Skin&Joint",
    requires_prescription: false,
  },
  {
    id: "vit-020",
    name: "Экстракт эхинацеи",
    description: "Растительный иммуностимулятор",
    price_sm: 210,
    weight_sm: 30,
    active_component_sm: 0,
    dosage_sm: 20,
    price_lg: 380,
    weight_lg: 60,
    active_component_lg: 0,
    dosage_lg: 40,
    rating: 4.1,
    is_promo: false,
    is_new: false,
    is_top: false,
    is_herbal: true,
    is_profit: true,
    old_price_sm: 0,
    old_price_lg: 0,
    promo_title: "",
    img_url: "/vitamins/vitamin-1.webp",
    category: "травяные сборы",
    manufacturer: "Phytoteka",
    requires_prescription: false,
  },
];

export default vitamins;